# automatically generated by the FlatBuffers compiler, do not modify

# namespace: 

import flatbuffers

class Contact(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsContact(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Contact()
        x.Init(buf, n + offset)
        return x

    # Contact
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Contact
    def ContactNumber(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Contact
    def ContactName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Contact
    def ContactEmail(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Contact
    def ContactCreatedTime(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

    # Contact
    def Hash(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Contact
    def UserId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Contact
    def DeviceId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ContactStart(builder): builder.StartObject(7)
def ContactAddContactNumber(builder, contactNumber): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(contactNumber), 0)
def ContactAddContactName(builder, contactName): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(contactName), 0)
def ContactAddContactEmail(builder, contactEmail): builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(contactEmail), 0)
def ContactAddContactCreatedTime(builder, contactCreatedTime): builder.PrependInt64Slot(3, contactCreatedTime, 0)
def ContactAddHash(builder, hash): builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(hash), 0)
def ContactAddUserId(builder, userId): builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(userId), 0)
def ContactAddDeviceId(builder, deviceId): builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(deviceId), 0)
def ContactEnd(builder): return builder.EndObject()
